name: 'TEST #79'
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  TEST:
    runs-on: ubuntu-latest
    steps:
      - uses: 10up/action-pr-automator@enhancement/79
        with:
          issue-welcome-message: |
            Welcome {author}! 👋 Thank you for opening your first issue! We're glad to have you here and appreciate your contribution. If you need any help or have questions, feel free to ask. Happy coding! 🚀
          pr-welcome-message: 🎉 Welcome {author}! 🎉 Thank you for your pull request! We're thrilled to see your involvement in our project. If you have any questions or need assistance, don't hesitate to ask. Keep up the great work! 👍

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
